### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pkatuwal** [thebinary/ported#2]
runtime error: invalid memory address or nil pointer dereference
## When
By Running This command
```
./ported -using http://ported.wlink.com.np:8888 -to 8080 -log.response.body
```
But it works after adding **:** on port number
```
./ported -using http://ported.wlink.com.np:8888 -to :8080 -log.response.body

```

![image](https://user-images.githubusercontent.com/5323815/88621889-3f732e00-d0c1-11ea-9d0d-f6b37133b8b4.png)

**Comment by thebinary** [comment]
thank you for the suggestion. fixed with merge #4
